name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - chromium/*

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-20.04
            v8: disabled
            cfg: Release
            cpu: x64
            artifact: pdfium-linux-x64
          - runner: ubuntu-20.04
            v8: disabled
            cfg: Release
            cpu: arm
            artifact: pdfium-linux-arm
            skip_test: true
          - runner: macos-10.15
            v8: disabled
            cfg: Release
            cpu: x64
            artifact: pdfium-darwin-x64
          - runner: macos-10.15
            v8: disabled
            cfg: Release
            cpu: arm64
            artifact: pdfium-darwin-arm64
            skip_test: true
          - runner: windows-2019
            v8: disabled
            cfg: Release
            cpu: x86
            artifact: pdfium-windows-x86
          - runner: windows-2019
            v8: disabled
            cfg: Release
            cpu: x64
            artifact: pdfium-windows-x64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set PDFium branch
        if: ${{ startsWith(github.ref, 'refs/tags/chromium/') }}
        run: echo "PDFium_BRANCH=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          cat >>$GITHUB_ENV <<END
          PDFium_V8=${{ matrix.v8 }}
          PDFium_CONFIGURATION=${{ matrix.cfg }}
          PDFium_TARGET_CPU=${{ matrix.cpu }}
          END
          steps/00-environment.sh
        shell: bash
      - name: Install (1/2)
        run: steps/01-install.sh
        shell: bash
      - name: Checkout PDFium
        run: steps/02-checkout.sh
        shell: bash
      - name: Apply patches
        run: steps/03-patch.sh
        shell: bash
      - name: Install (2/2)
        run: steps/04-install-extras.sh
        shell: bash
      - name: Configure build
        run: steps/05-configure.sh
        shell: bash
      - name: Build
        run: steps/06-build.sh
        shell: bash
      - name: Pack
        run: steps/07-pack.sh
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: staging/
      - name: Test
        run: ./test.sh
        shell: bash
        if: ${{ !matrix.skip_test }}
        env:
          TARGET_CPU: ${{ matrix.cpu }}
      - name: Upload tarball to GitHub Release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/chromium/') }}
        with:
          allowUpdates: true
          draft: true
          artifacts: pdfium*.tgz
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish Release
    if: ${{ startsWith(github.ref, 'refs/tags/chromium/') }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Write release body
      run: echo "This version was built with branch ${GITHUB_REF#refs/tags/} of PDFium" > RELEASE.md
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        bodyFile: RELEASE.md
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}
